add Activity.openInBrowser
Evgeny-Tobolich/Qr-scanner pull request #13
Opened 2021-03-23 17:01 UTC by EvgenyTobolich

2021-03-23 17:14 UTC, Wilzapps requested changes

2021-03-23 17:14 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +    if (Patterns.WEB_URL.matcher(string).matches()) {
А что если это не WEB_URL ? Я тебе оставлял в ТЗ к этой задаче описание, почитай его еще раз, пожалуйста

2021-03-24 08:21 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +    if (Patterns.WEB_URL.matcher(string).matches()) {
изменил

2021-03-24 08:57 UTC, Wilzapps requested changes
Требует внесения исправлений

2021-03-24 08:57 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +
лишняя пустая строка

2021-03-24 08:57 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +    if (Patterns.WEB_URL.matcher(string).matches()) OpenInBrowserAsURL(string)
исправь if-else согласно Code Convention
https://kotlinlang.org/docs/coding-conventions.html#conditional-statements

2021-03-24 08:57 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +fun Activity.openInBrowser(string: String) {
Ты внутри функции принимаешь параметр и далее сам определяешь как её обработать, т.е. для того, кто использует твой код все очень просто, а под капотом все немного сложнее. Как называется этот принцип ООП ?

2021-03-24 08:57 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +private fun Activity.OpenInBrowserAsURL(string: String) {
Исправь нейминг функции согласно CC
https://kotlinlang.org/docs/coding-conventions.html#function-names

2021-03-24 08:57 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +private fun Activity.OpenInBrowserAsURL(string: String) {
Функция не должна быть приватной, чтобы ты мог её использовать потворно

2021-03-24 08:57 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +    val url = if (!string.startsWith("http://") && !string.startsWith("https://"))
условие внутри if недостаточное, надо доработать ,чтобы обрабатывало все состояния (их 4, у тебя пока обрабатывается 2)

2021-03-24 08:57 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +    val intent = Intent(Intent.ACTION_VIEW).apply {
если внутри `apply` один вызов функции, то apply переносят на новую строку и пишут в одну строчку

2021-03-24 08:57 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +private fun Activity.OpenInBrowserAsQueryInGoogle(string: String) {
https://kotlinlang.org/docs/coding-conventions.html#function-names

2021-03-24 08:57 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +    val intent = Intent(Intent.ACTION_VIEW).apply {
apply

2021-03-24 08:57 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +        data = Uri.parse("http://www.google.com/search?q=$string")
я думал, что Google использует защищенный протокол) исправь на https, не пугай ребят с гугла)

2021-03-24 09:28 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +
удалил

2021-03-24 09:28 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +    if (Patterns.WEB_URL.matcher(string).matches()) OpenInBrowserAsURL(string)
изменил

2021-03-24 09:28 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +private fun Activity.OpenInBrowserAsURL(string: String) {
исправил

2021-03-24 09:28 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +private fun Activity.OpenInBrowserAsURL(string: String) {
исправил

2021-03-24 09:28 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +private fun Activity.OpenInBrowserAsQueryInGoogle(string: String) {
исправил

2021-03-24 09:46 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +    val url = if (!string.startsWith("http://") && !string.startsWith("https://"))
исправил

2021-03-24 09:46 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +    val intent = Intent(Intent.ACTION_VIEW).apply {
исправил

2021-03-24 09:46 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +        data = Uri.parse("http://www.google.com/search?q=$string")
исправил

2021-03-24 09:46 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +    val intent = Intent(Intent.ACTION_VIEW).apply {
исправил

2021-03-24 10:01 UTC, Wilzapps requested changes

2021-03-24 10:01 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +    private fun requestCameraPermissionErrorDialog() {
В рамках задачи по реализации экстеншен функции не должно быть правок в других классах, удаляй

2021-03-24 10:01 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +    if (Patterns.WEB_URL.matcher(string).matches()) {
Исправил не корректно

2021-03-24 10:01 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +    } else openInBrowserAsQueryInGoogle(string)
повторно надо внести правки

2021-03-24 10:01 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +    val url = if (
вообще не понял о чем тут условия внутри if'a, удаляй и сделай через when, должно быть 4 условия, проверка идет только на http/https

2021-03-24 10:01 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +    } else string
https://kotlinlang.org/docs/coding-conventions.html#control-flow-statements

2021-03-24 10:47 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +    } else string
изменил

2021-03-24 10:47 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +    val url = if (
изменил

2021-03-24 10:47 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +    } else openInBrowserAsQueryInGoogle(string)
изменил

2021-03-24 11:13 UTC, Wilzapps requested changes

2021-03-24 11:13 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +        !string.startsWith("http://") -> "https://$string"
В коде ошибки, например: 

если придет ссылка `https://google.com`,  то она станет `http://https://google.com`

2021-03-24 11:41 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +        !string.startsWith("http://") -> "https://$string"
исправил

2021-03-24 12:19 UTC, Wilzapps requested changes
Удалить git файлик, который сюда просочился (зачем?) и написать мне все состояния для условного цикла

2021-03-24 12:19 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +fun Activity.openInBrowserAsURL(string: String) {
Распиши мне в сообщениях все возможные состояния, которые могут быть с текстовкой и попробуем вместе разобраться. Пока это тоже надо переделывать

2021-03-24 14:45 UTC, closed without merging