ErrorDialog
Evgeny-Tobolich/Qr-scanner pull request #15
Opened 2021-03-25 10:03 UTC by EvgenyTobolich

2021-03-25 10:16 UTC, Wilzapps requested changes
Требует доработки. Диалог работает со статическим сообщением, а должен работать с динамическим, которое получает через аргументы как указано в прикрепленной статье в нужных строчках

2021-03-25 10:16 UTC, Wilzapps commented on app/src/main/res/values/strings.xml
> +    --camera permission dialog--
Хорошая идея добавить комментарии, но синтаксис не верный, надо исправить
https://stackoverflow.com/questions/3484643/comments-in-android-layout-xml/3484726

2021-03-25 10:16 UTC, Wilzapps commented on app/src/main/res/values/strings.xml
> +    <string name="undrstndbly">понятно</string>
undrstndbly ?

2021-03-25 10:16 UTC, Wilzapps commented on app/src/main/res/values/strings.xml
> +    <string name="error_dialog_message">Ошибка подключения камеры</string>
Какая еще ошибка подключения камеры ?

2021-03-25 10:16 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +            return ErrorDialog()
https://stackoverflow.com/questions/15459209/passing-argument-to-dialogfragment

2021-03-25 10:16 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +            return ErrorDialog()
https://stackoverflow.com/questions/15459209/passing-argument-to-dialogfragment

2021-03-25 10:16 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +            .setMessage(getString(R.string.error_dialog_message))
https://stackoverflow.com/questions/15459209/passing-argument-to-dialogfragment

2021-03-25 12:12 UTC, Wilzapps requested changes
Остались правки по исправлению чистоты кода. В целом вариант рабочий, но качество код надо улучшить как указано в комментариях

2021-03-25 12:12 UTC, Wilzapps commented on app/src/main/res/values/strings.xml
> +    <string name="got_it">понятно</string>
Достаточно использовать стандартный ОК для таких сообщений. android.R.string.ok

2021-03-25 12:12 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +            args.putString("string", string)
Ключ для аргумента должен быть вынесен в приватную константу

2021-03-25 12:12 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +            args.putString("throwable", throwable.message)
Этот метод должен использовать полиморфизм для своей реализации. Не имеет смысла для этого метода писать полную реализацию. Внутри этого метода тебе достаточно доставать из throwable сообщение и как String передавать в уже готовый newInstance предназначенный для String

2021-03-25 12:12 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +        val message = arguments?.getString("string") ?: arguments?.getString("throwable")
чтение сообщения из аргумента должно быть сделано через `lazy` делегат и без использования двух разных ключей. Для аргумента "сообщение" может быть только один ключ - ARG_MESSAGE, который и имеет смысл доставать

2021-03-25 12:31 UTC, EvgenyTobolich commented on app/src/main/res/values/strings.xml
> +    <string name="error_dialog_message">Ошибка подключения камеры</string>
удалил

2021-03-25 12:31 UTC, EvgenyTobolich commented on app/src/main/res/values/strings.xml
> +    <string name="undrstndbly">понятно</string>
изменил

2021-03-25 12:31 UTC, EvgenyTobolich commented on app/src/main/res/values/strings.xml
> +    --camera permission dialog--
исправил

2021-03-25 13:07 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +            return ErrorDialog()
добавил

2021-03-25 13:07 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +            return ErrorDialog()
добавил

2021-03-25 13:07 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +            .setMessage(getString(R.string.error_dialog_message))
добавил

2021-03-25 14:06 UTC, EvgenyTobolich commented on app/src/main/res/values/strings.xml
> +    <string name="got_it">понятно</string>
изменил

2021-03-25 14:06 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +            args.putString("throwable", throwable.message)
изменил

2021-03-25 14:06 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +        val message = arguments?.getString("string") ?: arguments?.getString("throwable")
заменил

2021-03-25 19:13 UTC, Wilzapps requested changes
Почти готово. Старайся чаще применять scope functions когда это упрощает код

2021-03-25 19:13 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +        private const val ARG_MESSAGE = "string"
ARG_MESSAGE = "ARG_MESSAGE" - это минор, но так все делают и просто привычнее такой вариант видеть

2021-03-25 19:13 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +        fun newInstance(string: String): ErrorDialog {
message: String

2021-03-25 19:13 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +            args.putString(ARG_MESSAGE, string)
apply вместо `args.*`

2021-03-25 19:13 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +            return errorDialog
ErrorDialog().apply { arguments = Bundle().apply{ putString(...) }}}

2021-03-25 19:13 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +        fun newInstance(throwable: Throwable): ErrorDialog {
Эту функцию перенести выше, чтобы последовательно можно было читать код

2021-03-25 19:13 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +        val message: String by lazy {
lazy на уровень класса. Ковычки тут зачем ?

2021-03-26 06:47 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +            args.putString("string", string)
изменил

2021-03-26 06:56 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +        private const val ARG_MESSAGE = "string"
исправил

2021-03-26 06:56 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +        fun newInstance(string: String): ErrorDialog {
исправил

2021-03-26 06:57 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +            args.putString(ARG_MESSAGE, string)
заменил

2021-03-26 06:57 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +            return errorDialog
изменил

2021-03-26 06:57 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +        fun newInstance(throwable: Throwable): ErrorDialog {
перенес

2021-03-26 06:57 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +        val message: String by lazy {
перенес

2021-03-26 14:24 UTC, Wilzapps approved these changes
поправить один минор и можно вливать

2021-03-26 14:24 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +    private val message: String by lazy { "${arguments?.getString(ARG_MESSAGE)}" }
companion object всегда идет первым в классе, а за ним идут все остальные переменные, т.к. object - это статика

2021-03-26 14:24 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +            return newInstance(throwable.message.toString())
вроде бы message это уже строка и `toString()` не имеет смысла

2021-03-26 15:22 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +    private val message: String by lazy { "${arguments?.getString(ARG_MESSAGE)}" }
переместил

2021-03-26 15:22 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +            return newInstance(throwable.message.toString())
изменил

2021-03-26 15:22 UTC, merged