add UseCase + Interactor
Evgeny-Tobolich/Qr-scanner pull request #19
Opened 2021-04-26 11:29 UTC by EvgenyTobolich

2021-04-26 12:28 UTC, Wilzapps requested changes
Требует доработки

2021-04-26 12:28 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/domain/scanner/UseCase.kt
> +interface UseCase<in ScannerViewModel, out ScanResult> {
Интересный вариант с дженериками, но он нарушает требования Clean Arch (нижние слои ничего не должны знать о верхних слоях), поэтому его теперь можно удалить

2021-04-26 12:28 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/domain/scanner/ProcessScanResultInteractor.kt
> +    override fun execute(input: ScannerViewModel): ScanResult {
В  моем понимании интерактор должен на вход принимать строку, а не всю ViewModel

2021-04-26 13:02 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/domain/scanner/UseCase.kt
> +interface UseCase<in ScannerViewModel, out ScanResult> {
удалил

2021-04-26 13:03 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/domain/scanner/ProcessScanResultInteractor.kt
> +    override fun execute(input: ScannerViewModel): ScanResult {
изменил

2021-04-26 15:38 UTC, Wilzapps requested changes
Требуется доработка (сейчас код явно не рабочий)

2021-04-26 15:38 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/domain/scanner/ProcessScanResultInteractor.kt
> +    private lateinit var isPhoneValidator: IsPhoneValidator
эти переменные нигде не инициализируются и при использовании этого класса ты получишь RuntimeException. Надо добавить инициализаию к этим свойствам, причем не в интеракторе, пускай (инициализация валидаторов) - не будет в ответственности интерактора. Интераткор лишь должен получать уже сконфигурированные экземпляры всех необходимых ему для работы классов

2021-04-26 18:11 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/domain/scanner/ProcessScanResultInteractor.kt
> +    private lateinit var isPhoneValidator: IsPhoneValidator
заменил на новый класс

2021-04-27 06:06 UTC, Wilzapps requested changes
В конструктор просто добавь

2021-04-27 08:51 UTC, Wilzapps approved these changes
Можно вливать

2021-04-27 08:51 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/domain/scanner/ProcessScanResultInteractor.kt
> +        isPhoneValidator.isValid(string) -> ScanResult.Phone(string)
минор: я бы еще добавил импорты, кажется так было бы лаконичнее

2021-04-27 09:01 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/domain/scanner/ProcessScanResultInteractor.kt
> +        isPhoneValidator.isValid(string) -> ScanResult.Phone(string)
добавил

2021-04-27 09:01 UTC, merged