add ViewModel
Evgeny-Tobolich/Qr-scanner pull request #20
Opened 2021-04-27 14:39 UTC by EvgenyTobolich

2021-04-27 14:52 UTC, Wilzapps approved these changes
Необходимо внести правки и добавить реализацию во ViewModel

2021-04-27 14:52 UTC, Wilzapps commented on app/build.gradle
> +    def lifecycle_version = "2.3.1"
Эту переменную надо двинуть к переменной `kotlin_version`

2021-04-27 14:52 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    val liveData: MutableLiveData<DecodeCallback> by lazy {
не понял для чего это - удали

2021-04-27 14:52 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    fun scanResult() {
название не понятное, функция должна начинаться с глагола и в крайних случаях уточняющее слово. У тебя тут может быть название `processScanResult`

2021-04-27 14:52 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    fun scanResult() {
Функция должна принимать результат сканирования, сейчас эта функция ни счет не работает

2021-04-27 14:52 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +        viewModel.liveData.observe(this, Observer {
Эта функция ничего не делает - удали

2021-04-28 09:16 UTC, EvgenyTobolich commented on app/build.gradle
> +    def lifecycle_version = "2.3.1"
переместил

2021-04-28 09:17 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    val liveData: MutableLiveData<DecodeCallback> by lazy {
удалил

2021-04-28 09:17 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    fun scanResult() {
переименовал

2021-04-28 09:17 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    fun scanResult() {
добавил

2021-04-28 09:17 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +        viewModel.liveData.observe(this, Observer {
удалил

2021-04-28 09:47 UTC, Wilzapps requested changes
Требуются доработки

2021-04-28 09:47 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +        viewModel.processScanResult(viewModel.liveData.toString())
Это не рабочий код -удали `viewModel.processScanResult(viewModel.liveData.toString())`

2021-04-28 09:47 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    private val _liveData = MutableLiveData<String>()
никаких нижних подчеркиваний в названии переменных

2021-04-28 09:47 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    val liveData: LiveData<String> = _liveData
название переменной слишком абстрактное, не понятно для чего оно - надо улучшить

2021-04-28 09:47 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    val liveData: LiveData<String> = _liveData
Тип у LiveData String - это не верно, у тебя уже есть готовая модель для LiveData и это не String

2021-04-28 09:47 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +        processScanResultInteractor.execute(string).let {
скоуп функции надо применять там где это имеет смысл, тут let точно лишняя

2021-04-28 09:47 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +            _liveData.value = it.toString()
тут почти все хорошо, но зачем из результата ты достаешь строку ?

2021-04-28 11:10 UTC, Wilzapps requested changes
Код не работает, необходимо доработать

2021-04-28 11:10 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    private val resultLiveData = MutableLiveData<DecodeCallback>()
Замечания:
- Есть приватная константа, но на её нельзя подписаться из активити - надо исправить
- Название до сих пор не ясное, слишком общее
- Тип у LiveData все еще не верный, не может она работать с DecodeCallback

2021-04-28 11:10 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    fun processScanResult(string: String) {
Можешь тут по строкам рассказать как работает функция ?

2021-04-28 11:10 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +        viewModel = ViewModelProvider(this).get(ScannerViewModel::class.java)
тут используется стандартная фабрика, но она упадет с ошибкой, т.к. ViewModel у тебя на вход принимает два параметра, а тут их нету. Как провайдер сможет тебе создать ViewModel ?

2021-04-28 11:10 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +        viewModel.processScanResult(codeScanner.decodeCallback.toString())
Тут ничего не изменилось с прошлого раза - удалить

2021-04-28 19:07 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +        viewModel.processScanResult(viewModel.liveData.toString())
удалил

2021-04-28 19:07 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    private val _liveData = MutableLiveData<String>()
исправил

2021-04-28 19:07 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    val liveData: LiveData<String> = _liveData
исправил

2021-04-28 19:07 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    val liveData: LiveData<String> = _liveData
исправил

2021-04-28 19:07 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +        processScanResultInteractor.execute(string).let {
удалил

2021-04-28 19:08 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +            _liveData.value = it.toString()
исправил

2021-04-28 19:08 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    private val resultLiveData = MutableLiveData<DecodeCallback>()
исправил

2021-04-28 19:08 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +        viewModel = ViewModelProvider(this).get(ScannerViewModel::class.java)
исправил

2021-04-28 19:08 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +        viewModel.processScanResult(codeScanner.decodeCallback.toString())
удалил

2021-04-29 07:45 UTC, Wilzapps approved these changes
Требуются доработки

2021-04-29 07:45 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    private val mutableLiveData = MutableLiveData<ScanResult>()
Мы же с тобой на созвоне дали нормальное название, а теперь опять не понятное название - надо исправить

2021-04-29 07:45 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    private val processScanResultInteractor: ProcessScanResultInteractor
Тут разобрался почему все работает ?

2021-04-29 07:45 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +    private lateinit var viewModel: ScannerViewModel
Здесь вместо lateinit var должно быть val и использоваться делегат `by viewModels`, как в статье с LiveData

2021-04-29 07:45 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +        viewModel.liveData.observe(this, Observer { scan ->
Observer тут указывать не обязательно (вроде тебе это и IDE подсказывает) - на исправить

2021-04-29 07:45 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +        viewModel.liveData.observe(this, Observer { scan ->
Опять же, я читаю код и тут подписка на `liveData` переменную и если бы я не знал изначально про что это, то не смог бы понять что тут происходит для этого и нужны нормальные нейминги для переменных

2021-04-29 07:45 UTC, Wilzapps commented on app/src/main/res/layout/scanner_activity.xml
> +                android:visibility="visible" />
Не надо указывать `android:visibility="visible"` это значение идет по умолчанию

2021-04-29 07:45 UTC, Wilzapps commented on app/src/main/res/layout/scanner_activity.xml
> +                android:text="@string/scanResultText_text"
у этой TextView заранее установлен текст и не понятно для чего он, т.к. название у ресурса не раскрывает его суть

2021-04-29 07:45 UTC, Wilzapps commented on app/src/main/res/values/strings.xml
> +    <string name="scanResultText_text"></string>
в ресурсах никакого camelCase, только может быть snake_case

2021-04-29 07:45 UTC, Wilzapps commented on app/src/main/res/values/strings.xml
> +    <string name="scanResultText_text"></string>
Текстовка пустая и бесполезная - надо удалить или исправить на что более практичное

2021-04-29 07:45 UTC, Wilzapps commented on app/src/main/res/values/strings.xml
> +    <string name="scanResultText_text"></string>
При создании строковых ресурсов не имеет смысл в названии текстовки указывать `button`, `text` и прочее, название ресурса должно привязывать к функциональности, а не реализации.
Например: share, copy, scan_hint

2021-04-29 08:54 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    private val mutableLiveData = MutableLiveData<ScanResult>()
такой нейминг тоже оговаривался, как приемлемый. Так и быть верну обратно)

2021-04-29 08:54 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +    private lateinit var viewModel: ScannerViewModel
сделано

2021-04-29 08:55 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +        viewModel.liveData.observe(this, Observer { scan ->
показывает, оставлял для себя. Удалил

2021-04-29 08:56 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +        viewModel.liveData.observe(this, Observer { scan ->
исправил

2021-04-29 09:26 UTC, EvgenyTobolich commented on app/src/main/res/layout/scanner_activity.xml
> +                android:visibility="visible" />
удалил

2021-04-29 09:31 UTC, EvgenyTobolich commented on app/src/main/res/values/strings.xml
> +    <string name="scanResultText_text"></string>
изменил

2021-04-29 09:31 UTC, EvgenyTobolich commented on app/src/main/res/values/strings.xml
> +    <string name="scanResultText_text"></string>
изменил

2021-04-29 09:31 UTC, EvgenyTobolich commented on app/src/main/res/values/strings.xml
> +    <string name="scanResultText_text"></string>
изменил

2021-04-29 09:33 UTC, EvgenyTobolich commented on app/src/main/res/layout/scanner_activity.xml
> +                android:text="@string/scanResultText_text"
удалил

2021-04-29 09:54 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    private val processScanResultInteractor: ProcessScanResultInteractor
Да. Потому что перед вызовом поля оно инициализируется в геттере, как объект данного класса. А геттер для того, чтобы сразу не инициализировать.

2021-04-29 10:25 UTC, Wilzapps requested changes
Еще миноры остались, старайся не повторять одни и те же ошибки, хотя бы не в тех же самых местах) Я уже по тем ошибкам, которые полностью расписывал - не оставлял развернутые комментарии и просто написал как должно быть, постарайся запомнить как это сделано и в будущем делай так же

2021-04-29 10:25 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    private val scanResultLiveData = MutableLiveData<ScanResult>()
scanResultMutableLiveData

2021-04-29 10:25 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    val scanReservliveData: LiveData<ScanResult> = scanResultLiveData
scanResultLiveData

2021-04-29 10:25 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    val scanReservliveData: LiveData<ScanResult> = scanResultLiveData
Что вообще значит резерв ?

2021-04-29 10:25 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +        viewModel.scanReservliveData.observe(this, { scan ->
лямбда, если она последняя в списке аргументов, - может быть вынесена за круглые скобки. Тут должно быть так

`viewModel.scanReservliveData.observe(this) { scan -> binding.scanResultText.text = scan.string }`

2021-04-29 10:25 UTC, Wilzapps commented on app/src/main/res/layout/scanner_activity.xml
> +                    android:text="@string/done_result"
@string/done

2021-04-29 10:25 UTC, Wilzapps commented on app/src/main/res/layout/scanner_activity.xml
>                      android:textColor="@color/done_green"
@color/green

2021-04-29 10:25 UTC, Wilzapps commented on app/src/main/res/values/strings.xml
> +    <string name="done_result">Готово!</string>
done

2021-04-29 10:25 UTC, Wilzapps commented on app/src/main/res/values/strings.xml
> +    <string name="copy_toast">Скопировано</string>
copied

2021-04-29 10:25 UTC, Wilzapps commented on app/src/main/res/values/strings.xml
> +    <string name="copy">копия</string>
<string name="copy">Скопировать</string>

2021-04-29 10:25 UTC, Wilzapps commented on app/src/main/res/values/strings.xml
> +    <string name="share">поделиться</string>
Поделиться

2021-04-29 10:32 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    private val scanResultLiveData = MutableLiveData<ScanResult>()
исправил

2021-04-29 10:32 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    val scanReservliveData: LiveData<ScanResult> = scanResultLiveData
исправил

2021-04-29 10:33 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    val scanReservliveData: LiveData<ScanResult> = scanResultLiveData
резервное поле

2021-04-29 10:34 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +        viewModel.scanReservliveData.observe(this, { scan ->
исправил

2021-04-29 10:35 UTC, EvgenyTobolich commented on app/src/main/res/layout/scanner_activity.xml
> +                    android:text="@string/done_result"
исправил

2021-04-29 10:35 UTC, EvgenyTobolich commented on app/src/main/res/layout/scanner_activity.xml
>                      android:textColor="@color/done_green"
исправил

2021-04-29 10:37 UTC, EvgenyTobolich commented on app/src/main/res/values/strings.xml
> +    <string name="share">поделиться</string>
исправил

2021-04-29 10:37 UTC, EvgenyTobolich commented on app/src/main/res/values/strings.xml
> +    <string name="copy">копия</string>
заменил

2021-04-29 10:37 UTC, EvgenyTobolich commented on app/src/main/res/values/strings.xml
> +    <string name="copy_toast">Скопировано</string>
исправил

2021-04-29 10:38 UTC, EvgenyTobolich commented on app/src/main/res/values/strings.xml
> +    <string name="done_result">Готово!</string>
исправил

2021-04-29 10:50 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    val scanResultliveData: LiveData<ScanResult> = scanResultMutableLiveData
L с большой должно быть :(

2021-04-29 10:50 UTC, Wilzapps commented on app/src/main/res/layout/scanner_activity.xml
> +                android:text="@string/copied"
Тут должно быть `copy`

2021-04-29 10:50 UTC, Wilzapps commented on app/src/main/res/values/strings.xml
> +    <string name="copy_toast">Скопировано</string>
Тут должно быть `copied`

2021-04-29 10:50 UTC, Wilzapps commented on app/src/main/res/values/strings.xml
> +    <string name="copied">Скопировать</string>
тут должно быть `copy`

2021-04-29 10:50 UTC, Wilzapps commented on app/src/main/res/values/strings.xml
> +    <string name="copied">Скопировать</string>
тут должно быть `copy`

2021-04-29 10:50 UTC, Wilzapps requested changes
Осталось исправить текстовки

2021-04-29 11:08 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    val scanResultliveData: LiveData<ScanResult> = scanResultMutableLiveData
исправил

2021-04-29 11:10 UTC, EvgenyTobolich commented on app/src/main/res/layout/scanner_activity.xml
> +                android:text="@string/copied"
исправил

2021-04-29 11:10 UTC, EvgenyTobolich commented on app/src/main/res/values/strings.xml
> +    <string name="copy_toast">Скопировано</string>
исправил

2021-04-29 11:10 UTC, EvgenyTobolich commented on app/src/main/res/values/strings.xml
> +    <string name="copied">Скопировать</string>
исправил

2021-04-29 11:10 UTC, EvgenyTobolich commented on app/src/main/res/values/strings.xml
> +    <string name="copied">Скопировать</string>
исправил

2021-04-29 11:17 UTC, Wilzapps approved these changes
Можно вливать

2021-04-29 11:19 UTC, merged