add screen result of scanning
Evgeny-Tobolich/Qr-scanner pull request #21
Opened 2021-04-29 19:59 UTC by EvgenyTobolich

2021-04-30 08:22 UTC, Wilzapps requested changes
Добавить renderScanResult

2021-04-30 08:22 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +            binding.openInBrowserButton.visibility = LinearLayout.VISIBLE
View.VISIBLE везде

2021-04-30 08:22 UTC, Wilzapps commented on app/src/main/res/values/strings.xml
> +    <string name="prompt">Наведите сканер на QR код</string>
Не `promt`, а `scanner_hint`, потому что `promt` слишком общее

2021-04-30 08:22 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
>          viewModel.scanResultLiveData.observe(this) { scan ->
Эта функция стала слишком большой и это надо исправить, не должно быть функций больше 15 строчек кода

2021-04-30 08:22 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +            binding.openInBrowserButton.visibility = LinearLayout.VISIBLE
Вместо этого у тебя должна быть функция `renderScanResult`, которая определяет видимость всех кнопок

2021-04-30 08:22 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +            binding.copyButton.setOnClickListener {
С кликами - не очень круто каждый раз устанавливать листенер, но с другой стороны вариант по лучше тут если и сделать то он будет сложнее и я не уверен, что тебе это понравится)

2021-05-04 08:01 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +            binding.openInBrowserButton.visibility = LinearLayout.VISIBLE
заменил

2021-05-04 08:01 UTC, EvgenyTobolich commented on app/src/main/res/values/strings.xml
> +    <string name="prompt">Наведите сканер на QR код</string>
заменил

2021-05-04 08:19 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +            binding.openInBrowserButton.visibility = LinearLayout.VISIBLE
добавил

2021-05-04 09:36 UTC, Wilzapps requested changes

2021-05-04 09:36 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +        if (binding.scanResultText.text != "") {
1. Не очень круто показывать все кнопки, если это не имеет смысла, мы должны показывать нужный набор кнопок на основе распознанной модели
2. У тебя в рендере не предсмутрено обнуление видимости кнопок (например: если сканирование началось заново - надо прятать кнопки, у тебя сейчас это не рализовано и надо добавить в этой же функции)

2021-05-04 09:36 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +    private fun renderScanResult(string: String) {
Твоя большая ошибка, что ты тут пытаешься использовать `String`, а не специально подготовленную модельку. Её ведь ты для этого и придумывал (URL, Text, Phone), чтобы тут (в том числе) и использовать для гибкой отрисовки интерфейса

2021-05-04 14:57 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +    private fun renderScanResult(string: String) {
изменил

2021-05-04 14:58 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +        if (binding.scanResultText.text != "") {
удалил

2021-05-05 03:44 UTC, Wilzapps requested changes
Исправить:
- Название функции
- Упростить функцию render
- Исправить отступы (либо забить, пока не критично)

Сразу влить правки и перейти к задачке по реализации `ScannerState`

2021-05-05 03:44 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +fun Activity.phone(string: String) {
callPhoneNumber
Функция всегда начинается с глагола

2021-05-05 03:44 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +        MutableLiveData<ScanResult?>()
MutableLiveData<>(), тип указывать не обязательно, всегда смотри на замечания IDE

2021-05-05 03:44 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    fun reset() {
resetScanResult

2021-05-05 03:44 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +            binding.scanResultText.text = scan?.string
почему текст устанавливается тут, а не в функции `renderScanResult` ? Она для этого и создавалась)

2021-05-05 03:44 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +            resetLiveData()
читаю `resetLiveData` и не могу понять что там внутри происходит - название должно описывать действие, название ради названия не имеет смысла

2021-05-05 03:44 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +                if (scan != null) openInBrowser(scan.string)
тут в другиях кнопках клик листенеры должны устанавливаться тогда и только тогда, когда `scan != null` не должно быть проверки внутри лямбды, это не верно и сложно поддерживать в будущем

2021-05-05 03:44 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +                if (codeScanner.isPreviewActive) codeScanner.startPreview()
тут вообще ничего не должно быть, чтобы клик по сканеру не запускал сканирование
`setOnClickListener { Unit }`

2021-05-05 03:44 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +    private fun renderScanResult(scanResult: ScanResult?) {
`Do not repeat yourself`

2021-05-05 03:44 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +        when (scanResult) {
Внутри `when` не должно быть дублирования кода, сейчас у тебя значения слишком сильно дублируются, это сложно поддерживать и модифицировать, подумай как упростить это до 10-15 строчек (максимум)

У тебя никогда не должно быть функции размером больше 15 строк

2021-05-05 03:44 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +        binding.newScan.setOnClickListener {
В целом не плохое решение, но добавь тут `//TODO: заменить на ScannerState`

2021-05-05 03:44 UTC, Wilzapps commented on app/src/main/res/layout/scanner_activity.xml
> +            android:layout_weight="0.6"
Дичь, но ладно)

2021-05-05 03:44 UTC, Wilzapps commented on app/src/main/res/layout/scanner_activity.xml
> +                android:layout_height="25dp"
размеры ширины или высоты всегда должны быть кратными 8dp, тут должно быть 24dp или 32dp

2021-05-05 03:44 UTC, Wilzapps commented on app/src/main/res/layout/scanner_activity.xml
> +                    android:layout_margin="1dp"
Не кратно 8dp

2021-05-05 03:44 UTC, Wilzapps commented on app/src/main/res/layout/scanner_activity.xml
> +                android:layout_margin="2dp"
Не кратно 8dp

2021-05-05 06:41 UTC, EvgenyTobolich commented on app/src/main/res/layout/scanner_activity.xml
> +                android:layout_margin="2dp"
изменил

2021-05-05 06:42 UTC, EvgenyTobolich commented on app/src/main/res/layout/scanner_activity.xml
> +                    android:layout_margin="1dp"
изменил

2021-05-05 06:42 UTC, EvgenyTobolich commented on app/src/main/res/layout/scanner_activity.xml
> +                android:layout_height="25dp"
изменил

2021-05-05 07:04 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +fun Activity.phone(string: String) {
переименовал

2021-05-05 07:05 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +        MutableLiveData<ScanResult?>()
удалил лишнее

2021-05-05 07:06 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    fun reset() {
изменил

2021-05-05 07:07 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +            binding.scanResultText.text = scan?.string
переместил

2021-05-05 07:11 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +                if (scan != null) openInBrowser(scan.string)
изменил

2021-05-05 07:14 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +                if (codeScanner.isPreviewActive) codeScanner.startPreview()
удалил весь with

2021-05-05 07:43 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +        binding.newScan.setOnClickListener {
добавил

2021-05-05 08:34 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +            resetLiveData()
переименовал

2021-05-05 08:34 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +    private fun renderScanResult(scanResult: ScanResult?) {
объединил в функцию

2021-05-05 08:35 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +        when (scanResult) {
объединил в доп функции

2021-05-05 08:37 UTC, Wilzapps requested changes
Не вижу правок с прошлых замечаний, но комментарии закрыты как выполненные

2021-05-05 08:37 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +import android.provider.ContactsContract
Зачем эта зависимость, если она нигде не используется ? Удалить если не надо

2021-05-05 08:37 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +        MutableLiveData<ScanResult?>()
Нет не удалил, все осталось как было

2021-05-05 08:37 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    private val scanResultMutableLiveData: MutableLiveData<ScanResult?> =
Повторное замечание, т.к. не исправлено

2021-05-05 08:37 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    fun reset() {
Не вижу нового названия, надо исправить если не сделао

2021-05-05 08:40 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +import android.provider.ContactsContract
удалил

2021-05-05 08:40 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    private val scanResultMutableLiveData: MutableLiveData<ScanResult?> =
удалил

2021-05-05 09:13 UTC, Wilzapps requested changes
Внести правки в Activity, возможно совместно со мной, т.к. у тебя решение уходит куда-то в сторону. Напиши как видишь решение и созвонимся

2021-05-05 09:13 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +@SuppressLint("QueryPermissionsNeeded")
Зачем тут сапрес ? Кажется он тут не нужен

2021-05-05 09:13 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +    if (intent.resolveActivity(packageManager) != null)
либо в одну строчку, либо добавить фигурные скобки, это требования Code Conventions

2021-05-05 09:13 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    private val scanResultMutableLiveData = MutableLiveData<ScanResult?>()
private val scanResultMutableLiveData: MutableLiveData<ScanResult?>() = MutableLiveData<>()

2021-05-05 09:13 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +    private fun isGoneButtons() {
C 5ого раза только понял почему такое название у функции. Название функции должно быть с глагола (это очень важно и я больше не буду это повторять, чтобы спустя пару дней ты попробовал разобраться в своем коде и захотел топить котят из-за не понимания что к чему)

2021-05-05 09:13 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +    private fun isGoneButtons() {
Функция может начинаться с `is` или `has` - тогда и только тогда, когда возвращает `Boolean`, во всех иных случаях - ТОЛЬКО глагол, это очень важно

2021-05-05 09:13 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +    private fun openDefultButtons(scanResult: ScanResult?) = when (scanResult) {
бесполезная функция

2021-05-05 09:13 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +    private fun isVisibleButtons() {
также бесполезная функция

2021-05-05 09:13 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +    private fun isGoneButtons() {
также бесполезная функция

2021-05-05 09:13 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +    private fun bindButtons(scanResult: ScanResult?) {
ты инициализируешь тут кнопки, а не байндишь (в будущем ты будешь использовать `bind` в названии метода, но тут это точно не подходит). Лучше будет дать название `initClickListeners`

2021-05-05 09:13 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +    private fun resetScanScreen() {
Тут, банально читая код я вижу следующее:
ViewModel сбрось результат сканирования
Сканер покажи превью
isGoneButtons() ???? Вообще не ясно чего она делает, я например тут ожидал, что эта функция возвращает какой-то `Boolean`
Покажите подсказку о начале сканирования

---------------------------

В этом и заключается важность правильного именования функций. Если нейминг не соблюдает простые правила, то читать такой код очень сложно и тебе же в будущем это будет доставлять дикий дискомфорт

2021-05-05 09:13 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +        isGoneButtons()
???

2021-05-05 09:13 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +        if (scanResult != null) {
Тут проверка не нужна, сам по суди. У тебя пришла моделька на основе которой ты должен что-то отрисовать.

2021-05-05 09:19 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +@SuppressLint("QueryPermissionsNeeded")
подсвечивает IDE

2021-05-05 09:22 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +    private val scanResultMutableLiveData = MutableLiveData<ScanResult?>()
подсвечивает IDE, что нужно добавить геттер или добавить в конструктор. Оставил как было

2021-05-05 09:23 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +    if (intent.resolveActivity(packageManager) != null)
не заметил, мой косяк

2021-05-06 15:37 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +        if (scanResult != null) {
удалил

2021-05-06 15:37 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +        isGoneButtons()
удалил

2021-05-06 15:38 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +    private fun isGoneButtons() {
удалил

2021-05-06 15:38 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +    private fun openDefultButtons(scanResult: ScanResult?) = when (scanResult) {
удалил

2021-05-06 15:38 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +    private fun isVisibleButtons() {
удалено

2021-05-06 15:39 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +    private fun bindButtons(scanResult: ScanResult?) {
переименовал

2021-05-06 15:39 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +    private fun resetScanScreen() {
изменено

2021-05-06 15:39 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +    private fun isGoneButtons() {
удалено

2021-05-06 15:39 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +    private fun isGoneButtons() {
удалено

2021-05-06 15:45 UTC, merged