Dev view model
Evgeny-Tobolich/Qr-scanner pull request #9
Opened 2021-03-22 14:29 UTC by EvgenyTobolich

2021-03-22 15:04 UTC, Wilzapps requested changes
Необходимо внести правки и залить исправления на повторное ревью. Перед началом работы над правками - обязательно надо созвониться и пройти по Git Flow вместе, чтобы не было проблем с Git'ом

2021-03-22 15:04 UTC, Wilzapps commented on app/.gitignore
> +*.iml
Для чего тут все эти доработки ? Вроде порешали, что они не нужны и достаточно только на уровне проекте в `gitingore` это добавить

2021-03-22 15:04 UTC, Wilzapps commented on app/build.gradle
> +    implementation "com.jakewharton.timber:timber:4.7.1"
У тебя есть стандартный Logcat и `android.util.Log`, поэтому добавлять Timber без надобности и понимания что это такое не вижу смысла. Надо удалить либо обосновать для чего он нужен и чем отличается от `android.util.Log`

2021-03-22 15:04 UTC, Wilzapps commented on app/src/main/AndroidManifest.xml
> +            android:screenOrientation="portrait"
что-то мне подсказывает, что тут не хватает `CTRL+ALT+L` :)

2021-03-22 15:04 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/QRScannerApplication.kt
> +        Timber.plant(Timber.DebugTree())
Опять же, если добавляешь `Timber`, то надо объяснить для чего он тебе нужен и чем лучше обычного `android.util.Log`

2021-03-22 15:04 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +class ErrorDialog {
Добавить, пожалуйста к классу `TODO("Will be implemented"), чтобы потом не потерять его

2021-03-22 15:04 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/RequestCameraPermissionDialog.kt
> +           val TAG = "RequestCameraPermissionDialog"::class.java.simpleName
Зачем название класса добавил в кавычки ?) Их тут быть не должно, ты из Class сделал String и тэг будет не тот, что ожидается

2021-03-22 15:04 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +fun ScannerActivity.copyBtnClick(view: View) {
Зачем тут входной параметр `view` ? Он нигде не используется и не нужен видимо, поэтому его надо удалить у всех трех функций.

2021-03-22 15:04 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +fun ScannerActivity.copyBtnClick(view: View) {
Экстеншен функции должны принимать на вход параметр String, а не View, чтобы с полученным на вход параметром String выполнить все необходимое

2021-03-22 15:04 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +        this, "Сopied!",
Строка `Сopied` должна уйти в ресурсы, никакого хардкода не должно быть

2021-03-22 15:04 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +    //TODO добавить текст для копирования
давай вынесем этот TODO на уровень экстеншен функции, чтобы он был ровно над названием функции

2021-03-22 15:04 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +fun ScannerActivity.shareBntClick(view: View) {
Сейчас у тебя логика шэра реализована не верно, поэтому давай удалим все содержимое функции, оставим показ тоста "Поделились" и добавим над названием функции TODO, что функцию только предстоит реализовать

2021-03-22 15:04 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +fun ScannerActivity.openInBrws(view: View) {
Сейчас у тебя логика открытия в браузере реализована не верно, поэтому давай удалим все содержимое функции, оставим показ тоста "Поделились" и добавим над названием функции TODO, что функцию только предстоит реализовать

2021-03-22 15:04 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +package tobolich.qr.scanner.common.utils
Т.к. комментов по этому классу получилось очень много вынесу это сюда. Названия у экстеншен функций не должно выглядеть как обработчик кликов. Название таких функций должно выглядеть как действие:
- copy()
- share()
- openInBrowser()

2021-03-22 15:04 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/domain/scanner/GetScannerHistoryInteractor.kt
> +class GetScannerHistoryInteractor {
Студия должна была подсветить, что фигурные скобки не нужны

2021-03-22 15:04 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +class ScannerViewModel : ViewModel() {
Аналогично, фигурные скобки не нужны, если внутри нету функций или свойств

2021-03-22 15:04 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +    private lateinit var binding: BottomHalfBinding
этот биндинг имеет слишком общее название и его можно перепутать с биндингом активити, давай дадим ему более явное название, например: "bottomHalfBinding"

2021-03-22 15:04 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +        binding = BottomHalfBinding.inflate(layoutInflater)
у тебя получается используется отдельный биндинг для второй половины ? Так не должно быть, по идее это вообще не должно было запуститься. У тебя должен быть один общий биндинг на всю активити, например ScannerActivityBinding, через который ты можешь получить все необходимые элементы одного экрана. Не нужен биндинг только для половины экрана

2021-03-22 15:04 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +            .show(
функция `show` и параметры должны поместиться в одну строку, если я правильно все прикинул

2021-03-22 15:04 UTC, Wilzapps commented on app/src/main/res/layout/bottom_half.xml
> +            android:background="#EAE5E5"
Цвета не должны указываться хардкодом, а должны использоваться через `@color/` ресерсы, чтобы их можно было переиспользовать в будущем

2021-03-22 15:04 UTC, Wilzapps commented on app/src/main/res/layout/bottom_half.xml
> +                    android:textSize="24dp"
размеры текста не пишут в dp, для этого используют sp. Почитай тут: http://developer.alexanderklimov.ru/android/theory/scales.php

2021-03-22 15:04 UTC, Wilzapps commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:4.1.3'
Если не знаешь для чего это нужно - не изменяй версию, а лучше почитай про разницу. Очень часто от одного этого изменения перестает собираться проект и потом будешь мучаться с исправлениями. Повышать версию Gradle, надо тогда и только тогда, когда уверен в том, что делаешь. Android Studio не всегда прав когда подсвечивает правки. Если у тебя проект собрался после этого - можешь оставить)

2021-03-22 16:38 UTC, EvgenyTobolich commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:4.1.3'
Собрался, запустил проверил

2021-03-22 16:48 UTC, EvgenyTobolich commented on app/src/main/res/layout/bottom_half.xml
> +                    android:textSize="24dp"
исправил

2021-03-22 16:54 UTC, EvgenyTobolich commented on app/src/main/res/layout/bottom_half.xml
> +            android:background="#EAE5E5"
исправил

2021-03-22 16:58 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +            .show(
исправил

2021-03-22 17:04 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +        binding = BottomHalfBinding.inflate(layoutInflater)
удалил лишний макет

2021-03-22 17:04 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +    private lateinit var binding: BottomHalfBinding
исправил

2021-03-22 17:05 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/presentation/ScannerViewModel.kt
> +class ScannerViewModel : ViewModel() {
исправил

2021-03-22 17:05 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/domain/scanner/GetScannerHistoryInteractor.kt
> +class GetScannerHistoryInteractor {
исправил

2021-03-22 17:17 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +fun ScannerActivity.openInBrws(view: View) {
исправил

2021-03-22 17:18 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +package tobolich.qr.scanner.common.utils
так и было, когда сделал реверт изменились названия на старые. 
Исправил.

2021-03-22 17:18 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +fun ScannerActivity.shareBntClick(view: View) {
исправил

2021-03-22 17:18 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +    //TODO добавить текст для копирования
исправил

2021-03-22 17:18 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +        this, "Сopied!",
добавил ид

2021-03-22 17:18 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +fun ScannerActivity.copyBtnClick(view: View) {
исправил

2021-03-22 17:18 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +fun ScannerActivity.copyBtnClick(view: View) {
удалил

2021-03-22 17:51 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +class ErrorDialog {
исправил

2021-03-22 17:51 UTC, EvgenyTobolich commented on app/src/main/AndroidManifest.xml
> +            android:screenOrientation="portrait"
исправил

2021-03-22 17:52 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/RequestCameraPermissionDialog.kt
> +           val TAG = "RequestCameraPermissionDialog"::class.java.simpleName
исправил

2021-03-22 17:58 UTC, EvgenyTobolich commented on app/.gitignore
> +*.iml
удалил

2021-03-22 18:27 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/QRScannerApplication.kt
> +        Timber.plant(Timber.DebugTree())
удалил класс, пока не вижу в нем смысла

2021-03-22 18:27 UTC, EvgenyTobolich commented on app/build.gradle
> +    implementation "com.jakewharton.timber:timber:4.7.1"
удалил

2021-03-23 09:09 UTC, Wilzapps requested changes
Уже почти все хорошо, необходимо исправить оставшиеся замечания и будем вливать, жду правки

2021-03-23 09:09 UTC, Wilzapps commented on app/.gitignore
> -/build
Этот файл не надо было удалять, а оставить таким какой он есть, поэтому верни и оставь как было сразу с одной строчкой - /build

2021-03-23 09:09 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +// TODO
К TODO всегда пишут через двоеточие, что в нем собираются сделать. Например: TODO: will be implemented

2021-03-23 09:09 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/RequestCameraPermissionDialog.kt
> +           val TAG = RequestCameraPermissionDialog::class.java.simpleName
CTRL+ALT+L, можешь самостоятельно это делать каждый раз, когда заканчиваешь работу с файлом

2021-03-23 09:09 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +//TODO добавить текст для копирования
Везде пишем комментарии либо на русском, либо на английском, смешивания быть не должно

2021-03-23 09:09 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +//TODO Refactor
Refactoring - переписывание уже рабочего функционала, поэтому не корректно там это писать. Должно быть `will be implemented` или `Еще не реализовано`

2021-03-23 09:09 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +// TODO Refactor
Тоже самое, это не рефакторинг

2021-03-23 09:09 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/domain/scanner/GetScannerHistoryInteractor.kt
> +class GetScannerHistoryInteractor
Можешь оставить комментарий, что этот класс сделан для примера и пока не имеет применения в проекте, чтобы потом не путаться

2021-03-23 09:09 UTC, Wilzapps commented on app/src/main/java/tobolich/qr/scanner/feature/scanner/ui/ScannerActivity.kt
> +    private lateinit var binding: ScannerActivityBinding
минор: биндинг пишут перед всеми остальными View Activity

------------------
минорные замечания не обязательные к исправлению, это такие незначительные замечания, которые бросаются в глаза, но являются чисто "вкусовщиной"

2021-03-23 09:09 UTC, Wilzapps commented on app/src/main/res/layout/scanner_activity.xml
> +                    android:textColor="@color/done_text"
минор: название ресурсы для цвета очень путает, т.к. названия для текста и цвета почти идентичные, может добавить постфикс `_color` или более абстрактное название дать "зеленый" или т.п.

2021-03-23 09:09 UTC, Wilzapps commented on app/src/main/res/layout/scanner_activity.xml
> +                    android:id="@+id/done_text"
идентификаторы при использовании ViewBinding должны быть написана при помощи camelCase, никаких snake_case

2021-03-23 09:09 UTC, Wilzapps commented on app/src/main/res/layout/scanner_activity.xml
> +                android:id="@+id/scan_result_text"
аналогично, должнен быть camelCase

2021-03-23 09:09 UTC, Wilzapps commented on app/src/main/res/layout/scanner_activity.xml
> +                android:textSize="16sp"
размер текста в ресурсы, название может быть например text_size_normal

2021-03-23 09:09 UTC, Wilzapps commented on app/src/main/res/values/strings.xml
> +    <string name="copy_toast_text">Сopied!</string>
Все строковые значения в ресурсах должны быть на одном языке, обязательно почитай эти статьи:
1. https://developer.android.com/guide/topics/resources/localization
2. http://developer.alexanderklimov.ru/android/locale.php

2021-03-23 09:25 UTC, EvgenyTobolich commented on app/src/main/res/values/strings.xml
> +    <string name="copy_toast_text">Сopied!</string>
изменил

2021-03-23 09:29 UTC, EvgenyTobolich commented on app/src/main/res/layout/scanner_activity.xml
> +                android:textSize="16sp"
добавил

2021-03-23 09:34 UTC, EvgenyTobolich commented on app/src/main/res/layout/scanner_activity.xml
> +                android:id="@+id/scan_result_text"
изменил

2021-03-23 09:35 UTC, EvgenyTobolich commented on app/src/main/res/layout/scanner_activity.xml
> +                    android:id="@+id/done_text"
изменил

2021-03-23 09:36 UTC, EvgenyTobolich commented on app/src/main/res/layout/scanner_activity.xml
> +                    android:textColor="@color/done_text"
изменил

2021-03-23 09:37 UTC, Wilzapps requested changes
Добавил еще одно замечание

2021-03-23 09:37 UTC, Wilzapps commented on app/src/main/res/layout/scanner_activity.xml
>                  android:onClick="copyBtnClick"
onClick из XML надо удалить, я видимо пропустил что-то, но этого не помню, чтобы добавляли

2021-03-23 09:38 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/utils/ActivityExt.kt
> +//TODO Refactor
изменил

2021-03-23 09:39 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/RequestCameraPermissionDialog.kt
> +           val TAG = RequestCameraPermissionDialog::class.java.simpleName
изменил

2021-03-23 09:39 UTC, EvgenyTobolich commented on app/src/main/java/tobolich/qr/scanner/common/dialogs/ErrorDialog.kt
> +// TODO
изменил

2021-03-23 09:42 UTC, EvgenyTobolich commented on app/.gitignore
> -/build
добавил

2021-03-23 09:43 UTC, Wilzapps requested changes
Еще одну правку докинул

2021-03-23 09:43 UTC, Wilzapps commented on app/src/main/res/layout/scanner_activity.xml
> +                android:id="@+id/openInBrowser"
`openInBrowser` + `Button` (забыл добавить, во всех остальных идентификаторах у тебя это проставлено

2021-03-23 09:48 UTC, EvgenyTobolich commented on app/src/main/res/layout/scanner_activity.xml
>                  android:onClick="copyBtnClick"
удалил

2021-03-23 09:49 UTC, EvgenyTobolich commented on app/src/main/res/layout/scanner_activity.xml
> +                android:id="@+id/openInBrowser"
исправил

2021-03-23 09:58 UTC, Wilzapps requested changes
Финальные правки и будем вливать

2021-03-23 09:58 UTC, Wilzapps commented on app/src/main/res/values/strings.xml
> +    <string name="open_in_browser">ОТКРЫТЬ ССЫЛКУ</string>
Не должно быть caps'а в ресурсах (за редким исключением), это решается при помощи использования атрибута `allCaps` на кнопке или тексте

2021-03-23 09:58 UTC, Wilzapps commented on app/src/main/res/values/colors.xml
> +    <color name="done_text_color_green">#19DA21</color>
Может проще уже прост green_done ?) Потому что у тебя тут уже намешано и контекстное и абстрактное

2021-03-23 10:03 UTC, EvgenyTobolich commented on app/src/main/res/values/strings.xml
> +    <string name="open_in_browser">ОТКРЫТЬ ССЫЛКУ</string>
исправил

2021-03-23 10:04 UTC, EvgenyTobolich commented on app/src/main/res/values/colors.xml
> +    <color name="done_text_color_green">#19DA21</color>
исправил

2021-03-23 10:09 UTC, Wilzapps approved these changes
Можно вливать

2021-03-23 10:12 UTC, merged